"""
assets.py — 资产库
覆盖：美股、A股、港股、期货、加密货币
分组扫描：每批约50个品种，避免超时
"""
from typing import Dict, Tuple

# ── TradingView 符号映射 ────────────────────────────────────────────
TV_MAP: Dict[str, str] = {
    # 大宗商品期货
    "GC=F":"COMEX:GC1!","SI=F":"COMEX:SI1!","CL=F":"NYMEX:CL1!",
    "BZ=F":"NYMEX:BB1!","NG=F":"NYMEX:NG1!","HG=F":"COMEX:HG1!",
    "ZW=F":"CBOT:ZW1!","ZC=F":"CBOT:ZC1!","ZS=F":"CBOT:ZS1!",
    "PL=F":"NYMEX:PL1!","PA=F":"NYMEX:PA1!","RB=F":"NYMEX:RB1!",
    "HO=F":"NYMEX:HO1!","LE=F":"CME:LE1!","HE=F":"CME:HE1!",
    "KC=F":"ICEUS:KC1!","CT=F":"ICEUS:CT1!","SB=F":"ICEUS:SB1!",
    "CC=F":"ICEUS:CC1!","OJ=F":"ICEUS:OJ1!",
    # 金融期货
    "ES=F":"CME:ES1!","NQ=F":"CME:NQ1!","YM=F":"CBOT:YM1!",
    "RTY=F":"CME:RTY1!","ZB=F":"CBOT:ZB1!","ZN=F":"CBOT:ZN1!",
    "ZF=F":"CBOT:ZF1!","ZT=F":"CBOT:ZT1!","6E=F":"CME:6E1!",
    "6J=F":"CME:6J1!","6B=F":"CME:6B1!","6A=F":"CME:6A1!",
    "6C=F":"CME:6C1!","VX=F":"CBOE:VX1!",
    # 外汇
    "EURUSD=X":"FX:EURUSD","GBPUSD=X":"FX:GBPUSD","USDJPY=X":"FX:USDJPY",
    "USDCNH=X":"FX:USDCNH","AUDUSD=X":"FX:AUDUSD","USDCAD=X":"FX:USDCAD",
    "USDCHF=X":"FX:USDCHF","NZDUSD=X":"FX:NZDUSD","EURGBP=X":"FX:EURGBP",
    "EURJPY=X":"FX:EURJPY","GBPJPY=X":"FX:GBPJPY","AUDJPY=X":"FX:AUDJPY",
    "USDSGD=X":"FX:USDSGD","USDHKD=X":"FX:USDHKD","USDKRW=X":"FX:USDKRW",
    "USDINR=X":"FX:USDINR","USDBRL=X":"FX:USDBRL","USDMXN=X":"FX:USDMXN",
    "USDZAR=X":"FX:USDZAR","XAUUSD=X":"TVC:GOLD","XAGUSD=X":"TVC:SILVER",
    # 全球指数
    "^GSPC":"SP:SPX","^NDX":"NASDAQ:NDX","^DJI":"DJ:DJI",
    "^RUT":"TVC:RUT","^VIX":"TVC:VIX",
    "000001.SS":"SSE:000001","399001.SZ":"SZSE:399001",
    "000300.SS":"SSE:000300","000016.SS":"SSE:000016",
    "^HSI":"TVC:HSI","^HSCE":"HKEX:HSCE",
    "^N225":"TVC:NI225","^FTSE":"TVC:UKX","^GDAXI":"TVC:DAX",
    "^FCHI":"EURONEXT:PX1","^STOXX50E":"TVC:SX5E",
    "^AXJO":"ASX:XJO","^KS11":"KRX:KOSPI",
    # 美股 - 科技
    "AAPL":"NASDAQ:AAPL","MSFT":"NASDAQ:MSFT","NVDA":"NASDAQ:NVDA",
    "AMZN":"NASDAQ:AMZN","GOOGL":"NASDAQ:GOOGL","META":"NASDAQ:META",
    "TSLA":"NASDAQ:TSLA","AVGO":"NASDAQ:AVGO","ORCL":"NYSE:ORCL",
    "AMD":"NASDAQ:AMD","INTC":"NASDAQ:INTC","QCOM":"NASDAQ:QCOM",
    "TXN":"NASDAQ:TXN","MU":"NASDAQ:MU","AMAT":"NASDAQ:AMAT",
    "LRCX":"NASDAQ:LRCX","KLAC":"NASDAQ:KLAC","MRVL":"NASDAQ:MRVL",
    "SMCI":"NASDAQ:SMCI","ARM":"NASDAQ:ARM","CRM":"NYSE:CRM",
    "NOW":"NYSE:NOW","ADBE":"NASDAQ:ADBE","INTU":"NASDAQ:INTU",
    "PANW":"NASDAQ:PANW","CRWD":"NASDAQ:CRWD","ZS":"NASDAQ:ZS",
    "SNOW":"NYSE:SNOW","PLTR":"NYSE:PLTR","NET":"NYSE:NET",
    "UBER":"NYSE:UBER","LYFT":"NASDAQ:LYFT","DASH":"NYSE:DASH",
    "SHOP":"NYSE:SHOP","SQ":"NYSE:SQ","PYPL":"NASDAQ:PYPL",
    "COIN":"NASDAQ:COIN","MSTR":"NASDAQ:MSTR","APP":"NASDAQ:APP",
    # 美股 - 金融
    "JPM":"NYSE:JPM","BAC":"NYSE:BAC","GS":"NYSE:GS","MS":"NYSE:MS",
    "WFC":"NYSE:WFC","C":"NYSE:C","BLK":"NYSE:BLK","SCHW":"NYSE:SCHW",
    "V":"NYSE:V","MA":"NYSE:MA","AXP":"NYSE:AXP",
    # 美股 - 医疗/消费
    "JNJ":"NYSE:JNJ","UNH":"NYSE:UNH","PFE":"NYSE:PFE","ABBV":"NYSE:ABBV",
    "LLY":"NYSE:LLY","MRK":"NYSE:MRK","BMY":"NYSE:BMY","AMGN":"NASDAQ:AMGN",
    "GILD":"NASDAQ:GILD","MRNA":"NASDAQ:MRNA","BNTX":"NASDAQ:BNTX",
    "AAON":"NASDAQ:AAON","WMT":"NYSE:WMT","COST":"NASDAQ:COST",
    "TGT":"NYSE:TGT","AMZN":"NASDAQ:AMZN","HD":"NYSE:HD","LOW":"NYSE:LOW",
    "MCD":"NYSE:MCD","SBUX":"NASDAQ:SBUX","NKE":"NYSE:NKE",
    # 美股 - 能源/工业
    "XOM":"NYSE:XOM","CVX":"NYSE:CVX","COP":"NYSE:COP","SLB":"NYSE:SLB",
    "OXY":"NYSE:OXY","MPC":"NYSE:MPC","PSX":"NYSE:PSX","VLO":"NYSE:VLO",
    "BA":"NYSE:BA","CAT":"NYSE:CAT","GE":"NYSE:GE","HON":"NASDAQ:HON",
    "LMT":"NYSE:LMT","RTX":"NYSE:RTX","NOC":"NYSE:NOC",
    # 中概/港股
    "BIDU":"NASDAQ:BIDU","PDD":"NASDAQ:PDD","JD":"NASDAQ:JD",
    "BABA":"NYSE:BABA","NTES":"NASDAQ:NTES","IQ":"NASDAQ:IQ",
    "EDU":"NYSE:EDU","TAL":"NYSE:TAL","NIO":"NYSE:NIO",
    "XPEV":"NYSE:XPEV","LI":"NASDAQ:LI","ZK":"NASDAQ:ZK",
    "9988.HK":"HKEX:9988","700.HK":"HKEX:700","3690.HK":"HKEX:3690",
    "9618.HK":"HKEX:9618","1810.HK":"HKEX:1810","9999.HK":"HKEX:9999",
    "2318.HK":"HKEX:2318","1299.HK":"HKEX:1299","3968.HK":"HKEX:3968",
    "2388.HK":"HKEX:2388","386.HK":"HKEX:386","857.HK":"HKEX:857",
    "941.HK":"HKEX:941","762.HK":"HKEX:762","1024.HK":"HKEX:1024",
    # A股ETF & 主要成分
    "510050.SS":"SSE:510050","510300.SS":"SSE:510300","159915.SZ":"SZSE:159915",
    "512880.SS":"SSE:512880","515050.SS":"SSE:515050",
    "600519.SS":"SSE:600519","601318.SS":"SSE:601318",
    "600036.SS":"SSE:600036","601166.SS":"SSE:601166",
    "000858.SZ":"SZSE:000858","002594.SZ":"SZSE:002594",
    "300750.SZ":"SZSE:300750","600900.SS":"SSE:600900",
    # 加密货币
    "BTC-USD":"BINANCE:BTCUSDT","ETH-USD":"BINANCE:ETHUSDT",
    "SOL-USD":"BINANCE:SOLUSDT","BNB-USD":"BINANCE:BNBUSDT",
    "XRP-USD":"BINANCE:XRPUSDT","ADA-USD":"BINANCE:ADAUSDT",
    "AVAX-USD":"BINANCE:AVAXUSDT","DOGE-USD":"BINANCE:DOGEUSDT",
    "DOT-USD":"BINANCE:DOTUSDT","MATIC-USD":"BINANCE:MATICUSDT",
    "LTC-USD":"BINANCE:LTCUSDT","LINK-USD":"BINANCE:LINKUSDT",
    "UNI-USD":"BINANCE:UNIUSDT","ATOM-USD":"BINANCE:ATOMUSDT",
    "TRX-USD":"BINANCE:TRXUSDT","XLM-USD":"BINANCE:XLMUSDT",
    "BCH-USD":"BINANCE:BCHUSDT","ETC-USD":"BINANCE:ETCUSDT",
    "FIL-USD":"BINANCE:FILUSDT","NEAR-USD":"BINANCE:NEARUSDT",
    "APT-USD":"BINANCE:APTUSDT","ARB-USD":"BINANCE:ARBUSDT",
    "OP-USD":"BINANCE:OPUSDT","SUI-USD":"BINANCE:SUIUSDT",
    "TON-USD":"BINANCE:TONUSDT","PEPE-USD":"BINANCE:PEPEUSDT",
}


def tv_symbol(ticker: str) -> str:
    return TV_MAP.get(ticker,
           ticker.replace("=X","").replace("=F","").replace("^",""))


def tv_url(ticker: str) -> str:
    return f"https://www.tradingview.com/chart/?symbol={tv_symbol(ticker)}"


# ════════════════════════════════════════════════════════════════════
# 品种分组（每批约50个，用户可选批次扫描）
# ════════════════════════════════════════════════════════════════════

ASSET_GROUPS: Dict[str, Dict[str, Tuple[str, str]]] = {

    "🥇 大宗商品期货": {
        "GC=F": ("黄金 Gold",        "futures"),
        "SI=F": ("白银 Silver",       "futures"),
        "CL=F": ("原油WTI",           "futures"),
        "BZ=F": ("布伦特原油",         "futures"),
        "NG=F": ("天然气",            "futures"),
        "HG=F": ("铜 Copper",         "futures"),
        "PL=F": ("铂金 Platinum",     "futures"),
        "PA=F": ("钯金 Palladium",    "futures"),
        "ZW=F": ("小麦 Wheat",        "futures"),
        "ZC=F": ("玉米 Corn",         "futures"),
        "ZS=F": ("大豆 Soybean",      "futures"),
        "KC=F": ("咖啡 Coffee",        "futures"),
        "CT=F": ("棉花 Cotton",        "futures"),
        "SB=F": ("糖 Sugar",          "futures"),
        "CC=F": ("可可 Cocoa",         "futures"),
        "OJ=F": ("橙汁 OJ",           "futures"),
        "RB=F": ("汽油 RBOB",         "futures"),
        "HO=F": ("取暖油",            "futures"),
    },

    "📈 金融期货 & 指数": {
        "ES=F":      ("E-mini S&P500", "futures"),
        "NQ=F":      ("E-mini NASDAQ", "futures"),
        "YM=F":      ("E-mini DOW",    "futures"),
        "RTY=F":     ("E-mini Russell","futures"),
        "ZB=F":      ("30Y国债期货",    "futures"),
        "ZN=F":      ("10Y国债期货",    "futures"),
        "VX=F":      ("VIX期货",        "futures"),
        "^GSPC":     ("S&P 500",        "index"),
        "^NDX":      ("NASDAQ 100",     "index"),
        "^DJI":      ("Dow Jones",      "index"),
        "^RUT":      ("Russell 2000",   "index"),
        "^VIX":      ("VIX恐慌指数",    "index"),
        "^N225":     ("日经225",         "index"),
        "^FTSE":     ("英国富时100",     "index"),
        "^GDAXI":    ("德国DAX",         "index"),
        "^FCHI":     ("法国CAC40",       "index"),
        "^STOXX50E": ("欧洲STOXX50",    "index"),
        "^AXJO":     ("澳大利亚ASX200", "index"),
        "^KS11":     ("韩国KOSPI",       "index"),
    },

    "💹 外汇 Forex": {
        "EURUSD=X": ("EUR/USD",  "forex"),
        "GBPUSD=X": ("GBP/USD",  "forex"),
        "USDJPY=X": ("USD/JPY",  "forex"),
        "USDCNH=X": ("USD/CNH",  "forex"),
        "AUDUSD=X": ("AUD/USD",  "forex"),
        "USDCAD=X": ("USD/CAD",  "forex"),
        "USDCHF=X": ("USD/CHF",  "forex"),
        "NZDUSD=X": ("NZD/USD",  "forex"),
        "EURGBP=X": ("EUR/GBP",  "forex"),
        "EURJPY=X": ("EUR/JPY",  "forex"),
        "GBPJPY=X": ("GBP/JPY",  "forex"),
        "AUDJPY=X": ("AUD/JPY",  "forex"),
        "USDSGD=X": ("USD/SGD",  "forex"),
        "USDHKD=X": ("USD/HKD",  "forex"),
        "USDKRW=X": ("USD/KRW",  "forex"),
        "USDINR=X": ("USD/INR",  "forex"),
        "USDBRL=X": ("USD/BRL",  "forex"),
        "USDMXN=X": ("USD/MXN",  "forex"),
        "USDZAR=X": ("USD/ZAR",  "forex"),
        "XAUUSD=X": ("黄金/USD",  "forex"),
        "XAGUSD=X": ("白银/USD",  "forex"),
    },

    "🇺🇸 美股 - 科技": {
        "AAPL":  ("Apple",          "us_stock"),
        "MSFT":  ("Microsoft",      "us_stock"),
        "NVDA":  ("NVIDIA",         "us_stock"),
        "GOOGL": ("Alphabet",       "us_stock"),
        "META":  ("Meta",           "us_stock"),
        "TSLA":  ("Tesla",          "us_stock"),
        "AVGO":  ("Broadcom",       "us_stock"),
        "AMD":   ("AMD",            "us_stock"),
        "INTC":  ("Intel",          "us_stock"),
        "QCOM":  ("Qualcomm",       "us_stock"),
        "TXN":   ("Texas Instr.",   "us_stock"),
        "MU":    ("Micron",         "us_stock"),
        "AMAT":  ("Applied Matls",  "us_stock"),
        "ARM":   ("ARM Holdings",   "us_stock"),
        "CRM":   ("Salesforce",     "us_stock"),
        "NOW":   ("ServiceNow",     "us_stock"),
        "ADBE":  ("Adobe",          "us_stock"),
        "INTU":  ("Intuit",         "us_stock"),
        "PANW":  ("Palo Alto",      "us_stock"),
        "CRWD":  ("CrowdStrike",    "us_stock"),
        "SNOW":  ("Snowflake",      "us_stock"),
        "PLTR":  ("Palantir",       "us_stock"),
        "NET":   ("Cloudflare",     "us_stock"),
        "UBER":  ("Uber",           "us_stock"),
        "SHOP":  ("Shopify",        "us_stock"),
        "SQ":    ("Block",          "us_stock"),
        "PYPL":  ("PayPal",         "us_stock"),
        "COIN":  ("Coinbase",       "us_stock"),
        "MSTR":  ("MicroStrategy",  "us_stock"),
        "APP":   ("AppLovin",       "us_stock"),
        "ORCL":  ("Oracle",         "us_stock"),
        "MRVL":  ("Marvell",        "us_stock"),
    },

    "🇺🇸 美股 - 金融/消费/能源": {
        "JPM":  ("JPMorgan",         "us_stock"),
        "BAC":  ("Bank of America",  "us_stock"),
        "GS":   ("Goldman Sachs",    "us_stock"),
        "MS":   ("Morgan Stanley",   "us_stock"),
        "WFC":  ("Wells Fargo",      "us_stock"),
        "V":    ("Visa",             "us_stock"),
        "MA":   ("Mastercard",       "us_stock"),
        "BLK":  ("BlackRock",        "us_stock"),
        "JNJ":  ("J&J",              "us_stock"),
        "UNH":  ("UnitedHealth",     "us_stock"),
        "LLY":  ("Eli Lilly",        "us_stock"),
        "PFE":  ("Pfizer",           "us_stock"),
        "ABBV": ("AbbVie",           "us_stock"),
        "MRK":  ("Merck",            "us_stock"),
        "MRNA": ("Moderna",          "us_stock"),
        "WMT":  ("Walmart",          "us_stock"),
        "COST": ("Costco",           "us_stock"),
        "MCD":  ("McDonald's",       "us_stock"),
        "SBUX": ("Starbucks",        "us_stock"),
        "NKE":  ("Nike",             "us_stock"),
        "XOM":  ("ExxonMobil",       "us_stock"),
        "CVX":  ("Chevron",          "us_stock"),
        "COP":  ("ConocoPhillips",   "us_stock"),
        "BA":   ("Boeing",           "us_stock"),
        "CAT":  ("Caterpillar",      "us_stock"),
        "GE":   ("GE Aerospace",     "us_stock"),
        "LMT":  ("Lockheed Martin",  "us_stock"),
        "RTX":  ("RTX Corp",         "us_stock"),
        "AMZN": ("Amazon",           "us_stock"),
        "HD":   ("Home Depot",       "us_stock"),
        "NFLX": ("Netflix",          "us_stock"),
        "DIS":  ("Disney",           "us_stock"),
    },

    "🇨🇳 中概股 & 港股": {
        "BIDU":    ("百度 Baidu",      "cn_stock"),
        "PDD":     ("拼多多 PDD",      "cn_stock"),
        "JD":      ("京东 JD.com",     "cn_stock"),
        "BABA":    ("阿里巴巴 ADR",    "cn_stock"),
        "NTES":    ("网易 NetEase",    "cn_stock"),
        "NIO":     ("蔚来 NIO",        "cn_stock"),
        "XPEV":    ("小鹏 XPEV",       "cn_stock"),
        "LI":      ("理想 Li Auto",    "cn_stock"),
        "EDU":     ("新东方 EDU",       "cn_stock"),
        "IQ":      ("爱奇艺 iQIYI",    "cn_stock"),
        "9988.HK": ("阿里巴巴 HK",     "cn_stock"),
        "700.HK":  ("腾讯 Tencent",    "cn_stock"),
        "3690.HK": ("美团 Meituan",    "cn_stock"),
        "9618.HK": ("京东 HK",         "cn_stock"),
        "1810.HK": ("小米 Xiaomi",     "cn_stock"),
        "9999.HK": ("网易 HK",         "cn_stock"),
        "2318.HK": ("中国平安",         "cn_stock"),
        "1299.HK": ("友邦保险 AIA",    "cn_stock"),
        "941.HK":  ("中国移动",         "cn_stock"),
        "762.HK":  ("中国联通",         "cn_stock"),
        "386.HK":  ("中石化 HK",        "cn_stock"),
        "857.HK":  ("中石油 HK",        "cn_stock"),
        "1024.HK": ("快手 Kuaishou",   "cn_stock"),
        "3968.HK": ("招商银行 HK",      "cn_stock"),
    },

    "🇨🇳 A股 核心": {
        "600519.SS": ("贵州茅台",  "a_stock"),
        "601318.SS": ("中国平安",  "a_stock"),
        "600036.SS": ("招商银行",  "a_stock"),
        "601166.SS": ("兴业银行",  "a_stock"),
        "000858.SZ": ("五粮液",    "a_stock"),
        "002594.SZ": ("比亚迪",    "a_stock"),
        "300750.SZ": ("宁德时代",  "a_stock"),
        "600900.SS": ("长江电力",  "a_stock"),
        "000001.SS": ("上证综指",  "a_stock"),
        "399001.SZ": ("深证成指",  "a_stock"),
        "000300.SS": ("沪深300",   "a_stock"),
        "000016.SS": ("上证50",    "a_stock"),
        "510050.SS": ("50ETF",     "a_stock"),
        "510300.SS": ("沪深300ETF","a_stock"),
        "159915.SZ": ("创业板ETF", "a_stock"),
        "512880.SS": ("证券ETF",   "a_stock"),
    },

    "₿ 加密货币": {
        "BTC-USD":   ("Bitcoin BTC",    "crypto"),
        "ETH-USD":   ("Ethereum ETH",   "crypto"),
        "SOL-USD":   ("Solana SOL",     "crypto"),
        "BNB-USD":   ("BNB",            "crypto"),
        "XRP-USD":   ("Ripple XRP",     "crypto"),
        "ADA-USD":   ("Cardano ADA",    "crypto"),
        "AVAX-USD":  ("Avalanche",      "crypto"),
        "DOGE-USD":  ("Dogecoin",       "crypto"),
        "DOT-USD":   ("Polkadot",       "crypto"),
        "LTC-USD":   ("Litecoin LTC",   "crypto"),
        "LINK-USD":  ("Chainlink",      "crypto"),
        "UNI-USD":   ("Uniswap",        "crypto"),
        "ATOM-USD":  ("Cosmos",         "crypto"),
        "TRX-USD":   ("TRON",           "crypto"),
        "XLM-USD":   ("Stellar",        "crypto"),
        "BCH-USD":   ("Bitcoin Cash",   "crypto"),
        "ETC-USD":   ("Ethereum Classic","crypto"),
        "FIL-USD":   ("Filecoin",       "crypto"),
        "NEAR-USD":  ("NEAR Protocol",  "crypto"),
        "APT-USD":   ("Aptos",          "crypto"),
        "ARB-USD":   ("Arbitrum",       "crypto"),
        "OP-USD":    ("Optimism",       "crypto"),
        "SUI-USD":   ("Sui",            "crypto"),
        "TON-USD":   ("Toncoin",        "crypto"),
        "PEPE-USD":  ("Pepe",           "crypto"),
        "MATIC-USD": ("Polygon MATIC",  "crypto"),
    },
}

# 快速预设（向后兼容旧版 scanner.py）
ASSETS: Dict[str, Tuple[str, str]] = {}
for _grp in ASSET_GROUPS.values():
    ASSETS.update(_grp)

TIMEFRAMES: Dict[str, Tuple[str, str]] = {
    "Daily":   ("1d",  "2y"),
    "Weekly":  ("1wk", "5y"),
    "Monthly": ("1mo", "10y"),
}

GROUP_NAMES = list(ASSET_GROUPS.keys())
